name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Publish
      uses: Squazz/publish-nuget@v2.5.6
      with:
       PROJECT_FILE_PATH: andrefmello91.EList/andrefmello91.EList.csproj
       NUGET_KEY: ${{secrets.NUGET_API_KEY}}
